version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3002:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    command: npm run dev
    networks:
      - app