import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ConfigProvider} from "antd"
import cn from "classnames"
import { GetServerToken } from "@/lib/auth";
import { redirect } from "next/navigation";
import { Header } from "@/components/partials/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <ConfigProvider 
          theme={{
            token : {
              colorPrimary: '#2ad49e'
            }
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
